/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVendorRouteImport } from './routes/_app.vendor'
import { Route as AppSuccessRouteImport } from './routes/_app.success'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppRentalsRouteImport } from './routes/_app.rentals'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppMessagesRouteImport } from './routes/_app.messages'
import { Route as AppImpactRouteImport } from './routes/_app.impact'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppVerifyIndexRouteImport } from './routes/_app.verify.index'
import { Route as AppVendorIndexRouteImport } from './routes/_app.vendor.index'
import { Route as AppInsuranceIndexRouteImport } from './routes/_app.insurance.index'
import { Route as AppVerifySelfieRouteImport } from './routes/_app.verify.selfie'
import { Route as AppVerifyReviewRouteImport } from './routes/_app.verify.review'
import { Route as AppVerifyIdRouteImport } from './routes/_app.verify.id'
import { Route as AppVerifyDoneRouteImport } from './routes/_app.verify.done'
import { Route as AppVendorRequestsRouteImport } from './routes/_app.vendor.requests'
import { Route as AppVendorNewRouteImport } from './routes/_app.vendor.new'
import { Route as AppVendorListingsRouteImport } from './routes/_app.vendor.listings'
import { Route as AppVendorEarningsRouteImport } from './routes/_app.vendor.earnings'
import { Route as AppThreadRequestIdRouteImport } from './routes/_app.thread.$requestId'
import { Route as AppRentIdRouteImport } from './routes/_app.rent.$id'
import { Route as AppPaymentIdRouteImport } from './routes/_app.payment.$id'
import { Route as AppItemIdRouteImport } from './routes/_app.item.$id'
import { Route as AppDeliveryRentalIdRouteImport } from './routes/_app.delivery.$rentalId'
import { Route as AppContractIdRouteImport } from './routes/_app.contract.$id'
import { Route as AppInsuranceValidationRentalIdRouteImport } from './routes/_app.insurance.validation.$rentalId'
import { Route as AppInsuranceRecordRentalIdRouteImport } from './routes/_app.insurance.record.$rentalId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVendorRoute = AppVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AppRoute,
} as any)
const AppSuccessRoute = AppSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppRentalsRoute = AppRentalsRouteImport.update({
  id: '/rentals',
  path: '/rentals',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppImpactRoute = AppImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyIndexRoute = AppVerifyIndexRouteImport.update({
  id: '/verify/',
  path: '/verify/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorIndexRoute = AppVendorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppInsuranceIndexRoute = AppInsuranceIndexRouteImport.update({
  id: '/insurance/',
  path: '/insurance/',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifySelfieRoute = AppVerifySelfieRouteImport.update({
  id: '/verify/selfie',
  path: '/verify/selfie',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyReviewRoute = AppVerifyReviewRouteImport.update({
  id: '/verify/review',
  path: '/verify/review',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyIdRoute = AppVerifyIdRouteImport.update({
  id: '/verify/id',
  path: '/verify/id',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyDoneRoute = AppVerifyDoneRouteImport.update({
  id: '/verify/done',
  path: '/verify/done',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorRequestsRoute = AppVendorRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorNewRoute = AppVendorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorListingsRoute = AppVendorListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppVendorEarningsRoute = AppVendorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppVendorRoute,
} as any)
const AppThreadRequestIdRoute = AppThreadRequestIdRouteImport.update({
  id: '/thread/$requestId',
  path: '/thread/$requestId',
  getParentRoute: () => AppRoute,
} as any)
const AppRentIdRoute = AppRentIdRouteImport.update({
  id: '/rent/$id',
  path: '/rent/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentIdRoute = AppPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppItemIdRoute = AppItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRentalIdRoute = AppDeliveryRentalIdRouteImport.update({
  id: '/delivery/$rentalId',
  path: '/delivery/$rentalId',
  getParentRoute: () => AppRoute,
} as any)
const AppContractIdRoute = AppContractIdRouteImport.update({
  id: '/contract/$id',
  path: '/contract/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInsuranceValidationRentalIdRoute =
  AppInsuranceValidationRentalIdRouteImport.update({
    id: '/insurance/validation/$rentalId',
    path: '/insurance/validation/$rentalId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInsuranceRecordRentalIdRoute =
  AppInsuranceRecordRentalIdRouteImport.update({
    id: '/insurance/record/$rentalId',
    path: '/insurance/record/$rentalId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/impact': typeof AppImpactRoute
  '/messages': typeof AppMessagesRoute
  '/new': typeof AppNewRoute
  '/profile': typeof AppProfileRoute
  '/rentals': typeof AppRentalsRoute
  '/search': typeof AppSearchRoute
  '/success': typeof AppSuccessRoute
  '/vendor': typeof AppVendorRouteWithChildren
  '/contract/$id': typeof AppContractIdRoute
  '/delivery/$rentalId': typeof AppDeliveryRentalIdRoute
  '/item/$id': typeof AppItemIdRoute
  '/payment/$id': typeof AppPaymentIdRoute
  '/rent/$id': typeof AppRentIdRoute
  '/thread/$requestId': typeof AppThreadRequestIdRoute
  '/vendor/earnings': typeof AppVendorEarningsRoute
  '/vendor/listings': typeof AppVendorListingsRoute
  '/vendor/new': typeof AppVendorNewRoute
  '/vendor/requests': typeof AppVendorRequestsRoute
  '/verify/done': typeof AppVerifyDoneRoute
  '/verify/id': typeof AppVerifyIdRoute
  '/verify/review': typeof AppVerifyReviewRoute
  '/verify/selfie': typeof AppVerifySelfieRoute
  '/insurance/': typeof AppInsuranceIndexRoute
  '/vendor/': typeof AppVendorIndexRoute
  '/verify/': typeof AppVerifyIndexRoute
  '/insurance/record/$rentalId': typeof AppInsuranceRecordRentalIdRoute
  '/insurance/validation/$rentalId': typeof AppInsuranceValidationRentalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/home': typeof AppHomeRoute
  '/impact': typeof AppImpactRoute
  '/messages': typeof AppMessagesRoute
  '/new': typeof AppNewRoute
  '/profile': typeof AppProfileRoute
  '/rentals': typeof AppRentalsRoute
  '/search': typeof AppSearchRoute
  '/success': typeof AppSuccessRoute
  '/contract/$id': typeof AppContractIdRoute
  '/delivery/$rentalId': typeof AppDeliveryRentalIdRoute
  '/item/$id': typeof AppItemIdRoute
  '/payment/$id': typeof AppPaymentIdRoute
  '/rent/$id': typeof AppRentIdRoute
  '/thread/$requestId': typeof AppThreadRequestIdRoute
  '/vendor/earnings': typeof AppVendorEarningsRoute
  '/vendor/listings': typeof AppVendorListingsRoute
  '/vendor/new': typeof AppVendorNewRoute
  '/vendor/requests': typeof AppVendorRequestsRoute
  '/verify/done': typeof AppVerifyDoneRoute
  '/verify/id': typeof AppVerifyIdRoute
  '/verify/review': typeof AppVerifyReviewRoute
  '/verify/selfie': typeof AppVerifySelfieRoute
  '/insurance': typeof AppInsuranceIndexRoute
  '/vendor': typeof AppVendorIndexRoute
  '/verify': typeof AppVerifyIndexRoute
  '/insurance/record/$rentalId': typeof AppInsuranceRecordRentalIdRoute
  '/insurance/validation/$rentalId': typeof AppInsuranceValidationRentalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/impact': typeof AppImpactRoute
  '/_app/messages': typeof AppMessagesRoute
  '/_app/new': typeof AppNewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/rentals': typeof AppRentalsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/success': typeof AppSuccessRoute
  '/_app/vendor': typeof AppVendorRouteWithChildren
  '/_app/contract/$id': typeof AppContractIdRoute
  '/_app/delivery/$rentalId': typeof AppDeliveryRentalIdRoute
  '/_app/item/$id': typeof AppItemIdRoute
  '/_app/payment/$id': typeof AppPaymentIdRoute
  '/_app/rent/$id': typeof AppRentIdRoute
  '/_app/thread/$requestId': typeof AppThreadRequestIdRoute
  '/_app/vendor/earnings': typeof AppVendorEarningsRoute
  '/_app/vendor/listings': typeof AppVendorListingsRoute
  '/_app/vendor/new': typeof AppVendorNewRoute
  '/_app/vendor/requests': typeof AppVendorRequestsRoute
  '/_app/verify/done': typeof AppVerifyDoneRoute
  '/_app/verify/id': typeof AppVerifyIdRoute
  '/_app/verify/review': typeof AppVerifyReviewRoute
  '/_app/verify/selfie': typeof AppVerifySelfieRoute
  '/_app/insurance/': typeof AppInsuranceIndexRoute
  '/_app/vendor/': typeof AppVendorIndexRoute
  '/_app/verify/': typeof AppVerifyIndexRoute
  '/_app/insurance/record/$rentalId': typeof AppInsuranceRecordRentalIdRoute
  '/_app/insurance/validation/$rentalId': typeof AppInsuranceValidationRentalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/home'
    | '/impact'
    | '/messages'
    | '/new'
    | '/profile'
    | '/rentals'
    | '/search'
    | '/success'
    | '/vendor'
    | '/contract/$id'
    | '/delivery/$rentalId'
    | '/item/$id'
    | '/payment/$id'
    | '/rent/$id'
    | '/thread/$requestId'
    | '/vendor/earnings'
    | '/vendor/listings'
    | '/vendor/new'
    | '/vendor/requests'
    | '/verify/done'
    | '/verify/id'
    | '/verify/review'
    | '/verify/selfie'
    | '/insurance/'
    | '/vendor/'
    | '/verify/'
    | '/insurance/record/$rentalId'
    | '/insurance/validation/$rentalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/home'
    | '/impact'
    | '/messages'
    | '/new'
    | '/profile'
    | '/rentals'
    | '/search'
    | '/success'
    | '/contract/$id'
    | '/delivery/$rentalId'
    | '/item/$id'
    | '/payment/$id'
    | '/rent/$id'
    | '/thread/$requestId'
    | '/vendor/earnings'
    | '/vendor/listings'
    | '/vendor/new'
    | '/vendor/requests'
    | '/verify/done'
    | '/verify/id'
    | '/verify/review'
    | '/verify/selfie'
    | '/insurance'
    | '/vendor'
    | '/verify'
    | '/insurance/record/$rentalId'
    | '/insurance/validation/$rentalId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signin'
    | '/signup'
    | '/welcome'
    | '/_app/home'
    | '/_app/impact'
    | '/_app/messages'
    | '/_app/new'
    | '/_app/profile'
    | '/_app/rentals'
    | '/_app/search'
    | '/_app/success'
    | '/_app/vendor'
    | '/_app/contract/$id'
    | '/_app/delivery/$rentalId'
    | '/_app/item/$id'
    | '/_app/payment/$id'
    | '/_app/rent/$id'
    | '/_app/thread/$requestId'
    | '/_app/vendor/earnings'
    | '/_app/vendor/listings'
    | '/_app/vendor/new'
    | '/_app/vendor/requests'
    | '/_app/verify/done'
    | '/_app/verify/id'
    | '/_app/verify/review'
    | '/_app/verify/selfie'
    | '/_app/insurance/'
    | '/_app/vendor/'
    | '/_app/verify/'
    | '/_app/insurance/record/$rentalId'
    | '/_app/insurance/validation/$rentalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vendor': {
      id: '/_app/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AppVendorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/success': {
      id: '/_app/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof AppSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rentals': {
      id: '/_app/rentals'
      path: '/rentals'
      fullPath: '/rentals'
      preLoaderRoute: typeof AppRentalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/impact': {
      id: '/_app/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof AppImpactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify/': {
      id: '/_app/verify/'
      path: '/verify'
      fullPath: '/verify/'
      preLoaderRoute: typeof AppVerifyIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/': {
      id: '/_app/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AppVendorIndexRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/insurance/': {
      id: '/_app/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof AppInsuranceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify/selfie': {
      id: '/_app/verify/selfie'
      path: '/verify/selfie'
      fullPath: '/verify/selfie'
      preLoaderRoute: typeof AppVerifySelfieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify/review': {
      id: '/_app/verify/review'
      path: '/verify/review'
      fullPath: '/verify/review'
      preLoaderRoute: typeof AppVerifyReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify/id': {
      id: '/_app/verify/id'
      path: '/verify/id'
      fullPath: '/verify/id'
      preLoaderRoute: typeof AppVerifyIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/verify/done': {
      id: '/_app/verify/done'
      path: '/verify/done'
      fullPath: '/verify/done'
      preLoaderRoute: typeof AppVerifyDoneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/requests': {
      id: '/_app/vendor/requests'
      path: '/requests'
      fullPath: '/vendor/requests'
      preLoaderRoute: typeof AppVendorRequestsRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/vendor/new': {
      id: '/_app/vendor/new'
      path: '/new'
      fullPath: '/vendor/new'
      preLoaderRoute: typeof AppVendorNewRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/vendor/listings': {
      id: '/_app/vendor/listings'
      path: '/listings'
      fullPath: '/vendor/listings'
      preLoaderRoute: typeof AppVendorListingsRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/vendor/earnings': {
      id: '/_app/vendor/earnings'
      path: '/earnings'
      fullPath: '/vendor/earnings'
      preLoaderRoute: typeof AppVendorEarningsRouteImport
      parentRoute: typeof AppVendorRoute
    }
    '/_app/thread/$requestId': {
      id: '/_app/thread/$requestId'
      path: '/thread/$requestId'
      fullPath: '/thread/$requestId'
      preLoaderRoute: typeof AppThreadRequestIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rent/$id': {
      id: '/_app/rent/$id'
      path: '/rent/$id'
      fullPath: '/rent/$id'
      preLoaderRoute: typeof AppRentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payment/$id': {
      id: '/_app/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof AppPaymentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/item/$id': {
      id: '/_app/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof AppItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/delivery/$rentalId': {
      id: '/_app/delivery/$rentalId'
      path: '/delivery/$rentalId'
      fullPath: '/delivery/$rentalId'
      preLoaderRoute: typeof AppDeliveryRentalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contract/$id': {
      id: '/_app/contract/$id'
      path: '/contract/$id'
      fullPath: '/contract/$id'
      preLoaderRoute: typeof AppContractIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insurance/validation/$rentalId': {
      id: '/_app/insurance/validation/$rentalId'
      path: '/insurance/validation/$rentalId'
      fullPath: '/insurance/validation/$rentalId'
      preLoaderRoute: typeof AppInsuranceValidationRentalIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insurance/record/$rentalId': {
      id: '/_app/insurance/record/$rentalId'
      path: '/insurance/record/$rentalId'
      fullPath: '/insurance/record/$rentalId'
      preLoaderRoute: typeof AppInsuranceRecordRentalIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppVendorRouteChildren {
  AppVendorEarningsRoute: typeof AppVendorEarningsRoute
  AppVendorListingsRoute: typeof AppVendorListingsRoute
  AppVendorNewRoute: typeof AppVendorNewRoute
  AppVendorRequestsRoute: typeof AppVendorRequestsRoute
  AppVendorIndexRoute: typeof AppVendorIndexRoute
}

const AppVendorRouteChildren: AppVendorRouteChildren = {
  AppVendorEarningsRoute: AppVendorEarningsRoute,
  AppVendorListingsRoute: AppVendorListingsRoute,
  AppVendorNewRoute: AppVendorNewRoute,
  AppVendorRequestsRoute: AppVendorRequestsRoute,
  AppVendorIndexRoute: AppVendorIndexRoute,
}

const AppVendorRouteWithChildren = AppVendorRoute._addFileChildren(
  AppVendorRouteChildren,
)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRoute
  AppImpactRoute: typeof AppImpactRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppNewRoute: typeof AppNewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRentalsRoute: typeof AppRentalsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSuccessRoute: typeof AppSuccessRoute
  AppVendorRoute: typeof AppVendorRouteWithChildren
  AppContractIdRoute: typeof AppContractIdRoute
  AppDeliveryRentalIdRoute: typeof AppDeliveryRentalIdRoute
  AppItemIdRoute: typeof AppItemIdRoute
  AppPaymentIdRoute: typeof AppPaymentIdRoute
  AppRentIdRoute: typeof AppRentIdRoute
  AppThreadRequestIdRoute: typeof AppThreadRequestIdRoute
  AppVerifyDoneRoute: typeof AppVerifyDoneRoute
  AppVerifyIdRoute: typeof AppVerifyIdRoute
  AppVerifyReviewRoute: typeof AppVerifyReviewRoute
  AppVerifySelfieRoute: typeof AppVerifySelfieRoute
  AppInsuranceIndexRoute: typeof AppInsuranceIndexRoute
  AppVerifyIndexRoute: typeof AppVerifyIndexRoute
  AppInsuranceRecordRentalIdRoute: typeof AppInsuranceRecordRentalIdRoute
  AppInsuranceValidationRentalIdRoute: typeof AppInsuranceValidationRentalIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRoute,
  AppImpactRoute: AppImpactRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppNewRoute: AppNewRoute,
  AppProfileRoute: AppProfileRoute,
  AppRentalsRoute: AppRentalsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSuccessRoute: AppSuccessRoute,
  AppVendorRoute: AppVendorRouteWithChildren,
  AppContractIdRoute: AppContractIdRoute,
  AppDeliveryRentalIdRoute: AppDeliveryRentalIdRoute,
  AppItemIdRoute: AppItemIdRoute,
  AppPaymentIdRoute: AppPaymentIdRoute,
  AppRentIdRoute: AppRentIdRoute,
  AppThreadRequestIdRoute: AppThreadRequestIdRoute,
  AppVerifyDoneRoute: AppVerifyDoneRoute,
  AppVerifyIdRoute: AppVerifyIdRoute,
  AppVerifyReviewRoute: AppVerifyReviewRoute,
  AppVerifySelfieRoute: AppVerifySelfieRoute,
  AppInsuranceIndexRoute: AppInsuranceIndexRoute,
  AppVerifyIndexRoute: AppVerifyIndexRoute,
  AppInsuranceRecordRentalIdRoute: AppInsuranceRecordRentalIdRoute,
  AppInsuranceValidationRentalIdRoute: AppInsuranceValidationRentalIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
